(function(g){var window=this;var qla=function(a,b){return g.gc(a,b)},h4=function(){},rla=function(a){if(a.wc&&"function"==typeof a.wc)return a.wc();
if(g.v(a))return a.split("");if(g.Ba(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.cc(a)},sla=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ba(a)||g.v(a))(0,g.C)(a,b,void 0);else{if(a.Gd&&"function"==typeof a.Gd)var c=a.Gd();else if(a.wc&&"function"==typeof a.wc)c=void 0;else if(g.Ba(a)||g.v(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.dc(a);d=rla(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},i4=function(a){g.Wo(a,"zx",g.Lb());
return a},j4=function(a,b,c){g.Aa(c)||(c=[String(c)]);
g.ap(a.o,b,c)},k4=function(a){if(!a.l&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},l4=function(a){var b;
(b=a.g)||(b={},k4(a)&&(b[0]=!0,b[1]=!0),b=a.g=b);return b},m4=function(a){return(a=k4(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},n4=function(a,b){return b+" ["+a.Y+" "+a.H+" "+a.getStatus()+"]"},tla=function(a){return"content-type"==a.toLowerCase()},o4=function(a){a.g&&a.N&&(a.g.ontimeout=null);
a.F&&(g.w.clearTimeout(a.F),a.F=null)},ula=function(a){return g.Vd&&g.Dc(9)&&g.wa(a.timeout)&&g.t(a.ontimeout)},p4=function(a){a.U||(a.U=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},q4=function(a,b){if(a.g){o4(a);
var c=a.g,d=a.T[0]?g.xa:null;a.g=null;a.T=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},r4=function(a,b){a.l=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.B=b;a.A=5;p4(a);q4(a)},s4=function(a){return a.g?a.g.readyState:0},t4=function(a){if(a.l&&"undefined"!=typeof g.oW)if(a.T[1]&&4==s4(a)&&2==a.getStatus())n4(a,"Local request error detected and ignored");
else if(a.G&&4==s4(a))g.Ig(a.Mu,0,a);else if(a.dispatchEvent("readystatechange"),4==s4(a)){n4(a,"Request complete");a.l=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.$g(String(a.H))[1]||null;if(!f&&g.w.self&&g.w.self.location){var k=g.w.self.location.protocol;f=k.substr(0,k.length-1)}e=!vla.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.A=6;try{var l=2<s4(a)?a.g.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";p4(a)}}finally{q4(a)}}},u4=function(a){g.Qf.call(this);
this.headers=new g.Lo;this.R=a||null;this.l=!1;this.T=this.g=null;this.Y=this.H="";this.A=0;this.B="";this.o=this.Z=this.G=this.U=!1;this.C=0;this.F=null;this.ga="";this.N=this.ba=!1},v4=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},wla=function(a,b){var c=[];
g.Fl(b,function(a){try{var b=g.yq.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.xq(b)&&c.push(a):c.push(a)},a);
return c},xla=function(a,b){var c=wla(a,b);
(0,g.C)(c,function(a){g.yq.prototype.remove.call(this,a)},a)},w4=function(a){if(a.Wc){if(a.Wc.locationOverrideToken)return{locationOverrideToken:a.Wc.locationOverrideToken};
if(null!=a.Wc.latitudeE7&&null!=a.Wc.longitudeE7)return{latitudeE7:a.Wc.latitudeE7,longitudeE7:a.Wc.longitudeE7}}return null},yla=function(a,b,c,d){var e=new g.Oo(null,void 0);
a&&g.Po(e,a);b&&g.Qo(e,b);c&&g.Ro(e,c);d&&(e.l=d);return e},x4=function(){this.g=[];
this.l=[]},y4=function(a){g.Xs[a]&&(a=g.Xs[a],(0,g.C)(a,function(a){g.Vs[a]&&delete g.Vs[a]}),a.length=0)},zla=function(a){var b=g.Us();
if(b)if(b.clear(a),a)y4(a);else for(var c in g.Xs)y4(c)},z4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.Lo;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Ala(this,a.capabilities||""),Bla(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},Ala=function(a,b){a.capabilities.clear();
(0,g.ke)(b.split(","),g.Ja(qla,Cla)).forEach(function(b){a.capabilities.add(b)})},Bla=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},A4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},B4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},C4=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Dla=function(a){return new A4(a)},D4=function(a){return g.Aa(a)?(0,g.E)(a,Dla):[]},E4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},F4=function(a){return g.Aa(a)?"["+(0,g.E)(a,E4).join(",")+"]":"null"},G4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Ela=function(a){return(0,g.E)(a,function(a){return{key:a.id,
name:a.name}})},H4=function(a,b){return g.Pa(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},I4=function(a,b){return g.Pa(a,function(a){return B4(a,b)})},Fla=function(){var a=(0,g.Wt)();
a&&xla(a,a.g.jf(!0))},J4=function(){var a=g.Zt("yt-remote-connected-devices")||[];
g.lb(a);return a},Gla=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.E)(a,function(a,b){return 0==b?a:a.substring(c.length)})},K4=function(a){g.Yt("yt-remote-connected-devices",a,86400)},M4=function(){if(L4)return L4;
var a=g.Zt("yt-remote-device-id");a||(a=G4(),g.Yt("yt-remote-device-id",a,31536E3));for(var b=J4(),c=1,d=a;g.Ta(b,d);)c++,d=a+"#"+c;return L4=d},N4=function(){var a=J4(),b=M4();
g.Ta(a,b);g.au()&&g.qb(a,b);a=Gla(a);if(0==a.length)try{g.Gt("remote_sid")}catch(c){}else try{g.Ft("remote_sid",a.join(","),-1)}catch(c){}},O4=function(){return g.Zt("yt-remote-session-browser-channel")},P4=function(){return g.Zt("yt-remote-local-screens")||[]},Q4=function(){g.Yt("yt-remote-lounge-token-expiration",!0,86400)},Hla=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.E)(P4(),function(a){return a.loungeToken}),c=(0,g.E)(a,function(a){return a.loungeToken});
(0,g.wo)(c,function(a){return!g.Ta(b,a)})&&Q4();
g.Yt("yt-remote-local-screens",a,31536E3)},Ila=function(a,b){g.Yt("yt-remote-session-browser-channel",a);
g.Yt("yt-remote-session-screen-id",b);var c=J4(),d=M4();g.Ta(c,d)||c.push(d);K4(c);N4()},R4=function(a){a||(g.$t("yt-remote-session-screen-id"),g.$t("yt-remote-session-video-id"));
N4();a=J4();g.Xa(a,M4());K4(a)},T4=function(){if(!S4){var a=g.Iq();
a&&(S4=new g.sq(a))}return S4?!!S4.get("yt-remote-use-staging-server"):!1},Jla=function(){var a=window.document.createElement("a");
g.td(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Qb(a)},Kla=function(a,b,c){c=void 0===c?null:c;
var d=g.ce("SCRIPT");d.id=a;d.onload=function(){b&&(0,window.setTimeout)(b,0)};
d.onreadystatechange=function(){switch(d.readyState){case "loaded":case "complete":d.onload()}};
c&&d.setAttribute("nonce",c);g.wd(d,g.Ae("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));a=window.document.getElementsByTagName("head")[0]||window.document.body;a.insertBefore(d,a.firstChild);return d},Lla=function(a){a=void 0===a?null:a;
var b=Jla(),c=window.document.getElementById(b),d=c&&g.hs(c,"loaded");d||c&&!d||(c=Kla(b,function(){g.hs(c,"loaded")||(g.gs(c,"loaded","true"),g.at(b),g.gr(g.Ja(zla,b),0))},a))},Mla=function(){var a=void 0===a?null:a;
window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):Lla(a)},U4=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},V4=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},X4=function(a){a.length?W4(a.shift(),function(){X4(a)}):Y4()},Nla=function(a){return"chrome-extension://"+a+Z4},W4=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},$4=function(a){return 0<=window.navigator.userAgent.indexOf(a)},Y4=function(){var a=V4();
a&&a(!1,"No cast extension found")},a5=function(){if(Ola){var a=2,b=V4(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;W4("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",Y4,c)}},Pla=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(a5(),a({command:"cast.sender.init"}))},Qla=function(){a5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);X4(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+Z4,"//www.gstatic.com/eureka/clank"+Z4])},b5=function(a,b,c){g.H.call(this);
this.C=null!=c?(0,g.A)(a,c):a;this.Sc=b;this.B=(0,g.A)(this.FC,this);this.g=!1;this.l=0;this.o=this.Ca=null;this.A=[]},c5=function(){},d5=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.C=d||1;this.A=45E3;this.ca=new g.bp(this);this.l=new g.Hg;this.l.setInterval(250)},f5=function(a,b,c){a.oi=1;
a.ug=i4(b.clone());a.Eh=c;a.B=!0;e5(a,null)},g5=function(a,b,c,d,e){a.oi=1;
a.ug=i4(b.clone());a.Eh=null;a.B=c;e&&(a.nz=!1);e5(a,d)},e5=function(a,b){a.Ui=(0,g.D)();
h5(a);a.Kg=a.ug.clone();j4(a.Kg,"t",a.C);a.Yk=0;a.sc=a.g.Mo(a.g.Pk()?b:null);0<a.vp&&(a.vn=new g.Lm((0,g.A)(a.uA,a,a.sc),a.vp));a.ca.ea(a.sc,"readystatechange",a.PL);var c=a.jh?g.oc(a.jh):{};a.Eh?(a.co="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.sc.send(a.Kg,a.co,a.Eh,c)):(a.co="GET",a.nz&&!g.Xd&&(c.Connection="close"),a.sc.send(a.Kg,a.co,null,c));a.g.ye(1)},o5=function(a,b,c){for(var d=!0;!a.Zg&&a.Yk<c.length;){var e=Rla(a,c);
if(e==i5){4==b&&(a.vg=4,j5(15),d=!1);break}else if(e==k5){a.vg=4;j5(16);d=!1;break}else l5(a,e)}4==b&&0==c.length&&(a.vg=1,j5(17),d=!1);a.Ce=a.Ce&&d;d||(m5(a),n5(a))},Rla=function(a,b){var c=a.Yk,d=b.indexOf("\n",c);
if(-1==d)return i5;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return k5;d+=1;if(d+c>b.length)return i5;var e=b.substr(d,c);a.Yk=d+c;return e},r5=function(a,b){a.Ui=(0,g.D)();
h5(a);var c=b?window.location.hostname:"";a.Kg=a.ug.clone();g.Wo(a.Kg,"DOMAIN",c);g.Wo(a.Kg,"t",a.C);try{a.Ee=new window.ActiveXObject("htmlfile")}catch(n){m5(a);a.vg=7;j5(22);n5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in p5)k=p5[l];else if(l in q5)k=p5[l]=q5[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
p5[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.xd(g.Oc("b/12014412"),d+"</body></html>");a.Ee.open();a.Ee.write(g.nd(c));a.Ee.close();a.Ee.parentWindow.m=(0,g.A)(a.jL,a);a.Ee.parentWindow.d=(0,g.A)(a.yy,a,!0);a.Ee.parentWindow.rpcClose=(0,g.A)(a.yy,a,!1);c=a.Ee.createElement("DIV");a.Ee.parentWindow.document.body.appendChild(c);d=g.Zc(a.Kg.toString());d=g.Fb(g.Wc(d));d=g.xd(g.Oc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.sd(c,g.nd(d));a.g.ye(1)},h5=function(a){a.ws=(0,g.D)()+
a.A;
s5(a,a.A)},s5=function(a,b){if(null!=a.fj)throw Error("WatchDog timer not null");
a.fj=t5((0,g.A)(a.uL,a),b)},u5=function(a){a.fj&&(g.w.clearTimeout(a.fj),a.fj=null)},n5=function(a){a.g.Ku()||a.Zg||a.g.cn(a)},m5=function(a){u5(a);
g.lf(a.vn);a.vn=null;a.l.stop();g.dp(a.ca);if(a.sc){var b=a.sc;a.sc=null;b.abort();b.dispose()}a.Ee&&(a.Ee=null)},l5=function(a,b){try{a.g.ny(a,b),a.g.ye(4)}catch(c){}},w5=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;v5(a,b,function(e){e?c(!0):g.w.setTimeout(function(){w5(a,b,c,d,f)},f)})}},v5=function(a,b,c){var d=new window.Image;
d.onload=function(){try{x5(d),c(!0)}catch(e){}};
d.onerror=function(){try{x5(d),c(!1)}catch(e){}};
d.onabort=function(){try{x5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{x5(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},x5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},y5=function(a){this.g=a;
this.l=new c5},A5=function(a){var b=z5(a.g,a.nj,"/mail/images/cleardot.gif");
i4(b);w5(b.toString(),5E3,(0,g.A)(a.bC,a),3,2E3);a.ye(1)},C5=function(a){var b=a.g.H;
if(null!=b)j5(5),b?(j5(11),B5(a.g,a,!1)):(j5(12),B5(a.g,a,!0));else if(a.Od=new d5(a,void 0,void 0,void 0),a.Od.jh=a.tp,b=a.g,b=z5(b,b.Pk()?a.Vj:null,a.up),j5(5),!g.Vd||g.Fc(10))j4(b,"TYPE","xmlhttp"),g5(a.Od,b,!1,a.Vj,!1);else{j4(b,"TYPE","html");var c=a.Od;a=!!a.Vj;c.oi=3;c.ug=i4(b.clone());r5(c,a)}},D5=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new c5;this.G=a||null;this.H=null!=b?b:null;this.C=c||!1},Sla=function(a,b){this.g=a;
this.map=b;this.context=null},E5=function(a){g.nf.call(this,"statevent",a)},F5=function(a,b){g.nf.call(this,"timingevent",a);
this.size=b},G5=function(a){g.nf.call(this,"serverreachability",a)},K5=function(a){H5(a);
if(3==a.g){var b=a.Bk++,c=a.Vl.clone();g.Wo(c,"SID",a.o);g.Wo(c,"RID",b);g.Wo(c,"TYPE","terminate");I5(a,c);b=new d5(a,a.o,b,void 0);b.oi=2;b.ug=i4(c.clone());(new window.Image).src=b.ug;b.Ui=(0,g.D)();h5(b)}J5(a)},M5=function(a){a.pC(1,0);
a.Vl=z5(a,null,a.rp);L5(a)},H5=function(a){a.kg&&(a.kg.abort(),a.kg=null);
a.Sb&&(a.Sb.cancel(),a.Sb=null);a.mf&&(g.w.clearTimeout(a.mf),a.mf=null);N5(a);a.ud&&(a.ud.cancel(),a.ud=null);a.pg&&(g.w.clearTimeout(a.pg),a.pg=null)},O5=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new Sla(a.vH++,b));2!=a.g&&3!=a.g||L5(a)},L5=function(a){a.ud||a.pg||(a.pg=t5((0,g.A)(a.vy,a),0),a.ii=0)},R5=function(a,b){if(1==a.g){if(!b){a.Bk=Math.floor(1E5*Math.random());
var c=a.Bk++,d=new d5(a,"",c,void 0);d.jh=null;var e=P5(a),f=a.Vl.clone();g.Wo(f,"RID",c);g.Wo(f,"CVER","1");I5(a,f);f5(d,f,e);a.ud=d;a.g=2}}else 3==a.g&&(b?Q5(a,b):0==a.l.length||a.ud||Q5(a))},Q5=function(a,b){if(b)if(6<a.ah){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.Bk-1;var d=P5(a)}else c=b.F,d=b.Eh;else c=a.Bk++,d=P5(a);var e=a.Vl.clone();g.Wo(e,"SID",a.o);g.Wo(e,"RID",c);g.Wo(e,"AID",a.zi);I5(a,e);c=new d5(a,a.o,c,a.ii+1);c.jh=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ud=c;f5(c,e,d)},I5=function(a,b){if(a.Qc){var c=a.Qc.vu();
c&&g.Xb(c,function(a,c){g.Wo(b,c,a)})}},P5=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.ah&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.ah?e:f-d;try{g.Xb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},S5=function(a){a.Sb||a.mf||(a.F=1,a.mf=t5((0,g.A)(a.ty,a),0),a.bi=0)},U5=function(a){if(a.Sb||a.mf||3<=a.bi)return!1;
a.F++;a.mf=t5((0,g.A)(a.ty,a),T5(a,a.bi));a.bi++;return!0},B5=function(a,b,c){a.ao=c;
a.Re=b.yf;a.C||M5(a)},N5=function(a){null!=a.eh&&(g.w.clearTimeout(a.eh),a.eh=null)},T5=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},W5=function(a,b){if(2==b||9==b){var c=null;
a.Qc&&(c=null);var d=(0,g.A)(a.pM,a);c||(c=new g.Oo("//www.google.com/images/cleardot.gif"),i4(c));v5(c.toString(),1E4,d)}else j5(2);V5(a,b)},V5=function(a,b){a.g=0;
a.Qc&&a.Qc.Ht(b);J5(a);H5(a)},J5=function(a){a.g=0;
a.Re=-1;if(a.Qc)if(0==a.A.length&&0==a.l.length)a.Qc.Do();else{g.ab(a.A);var b=g.ab(a.l);a.A.length=0;a.l.length=0;a.Qc.Do(b)}},z5=function(a,b,c){var d=g.Xo(c);
if(""!=d.g)b&&g.Qo(d,b+"."+d.g),g.Ro(d,d.B);else{var e=window.location;d=yla(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Dj&&g.Xb(a.Dj,function(a,b){g.Wo(d,b,a)});
g.Wo(d,"VER",a.ah);I5(a,d);return d},t5=function(a,b){if(!g.Ca(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},j5=function(a){X5.dispatchEvent(new E5(X5,a))},Y5=function(){},Tla=function(a,b){this.action=a;
this.params=b||{}},Z5=function(a,b){g.H.call(this);
this.g=new g.M(this.cL,0,this);g.I(this,this.g);this.Sc=5E3;this.l=0;if(g.Ca(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ca(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},$5=function(a,b,c){this.N=a;
this.C=b;this.o=new g.rq;this.l=new Z5(this.SM,this);this.g=null;this.J=!1;this.B=null;this.H="";this.G=this.A=0;this.F=[];this.T=c||!1},Ula=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.ao,sessionId:a.g.o,arrayId:a.g.zi}},a6=function(a,b){a.G=b||0;
a.l.stop();a.g&&(3==a.g.g&&R5(a.g),K5(a.g));a.G=0},b6=function(a){return!!a.g&&3==a.g.g},Vla=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},c6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.ch(a)||"";b&&(this.port=":"+b);this.domain=g.bh(a)||"";a=g.Vb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Pb(a,"10.0")&&(this.l=!1))},d6=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.lh(c+b,{})},e6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ja(a.A,d,!0),onError:g.Ja(a.o,e),kd:g.Ja(a.B,e)};c&&(a.jb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.yr(b,a)},Wla=function(){var a=f6;
g6();h6.push(a);i6(h6)},j6=function(a,b){g6();
var c=h6,d=Xla(a,String(b));0==c.length?Yla(d):(i6(c),(0,g.C)(c,function(a){a(d)}))},g6=function(){h6||(h6=g.z("yt.mdx.remote.debug.handlers_")||[],g.y("yt.mdx.remote.debug.handlers_",h6,void 0))},Yla=function(a){var b=(k6+1)%50;
k6=b;l6[b]=a;m6||(m6=49==b)},i6=function(a){var b=l6;
if(b[0]){var c=k6,d=m6?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
l6=Array(50);k6=-1;m6=!1}},Xla=function(a,b){var c=((0,g.D)()-Zla)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},n6=function(a){g.O.call(this);
this.F=a;this.g=[]},o6=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},$la=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.ke)(a.g,function(a){return!!H4(b,a)});
for(var d=0,e=b.length;d<e;d++)c=o6(a,b[d])||c;return c},ama=function(a,b){var c=a.g.length;
a.g=(0,g.ke)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},p6=function(a,b,c,d){g.O.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.Ca=window.NaN},r6=function(a){n6.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;q6(this);this.info("Initializing with "+F4(this.g))},s6=function(a){if(a.g.length){var b=(0,g.E)(a.g,function(a){return a.id}),c=d6(a.o,"/pairing/get_lounge_token_batch");
e6(a.o,c,{screen_ids:b.join(",")},(0,g.A)(a.QC,a),(0,g.A)(a.PC,a))}},q6=function(a){var b=D4(P4());
b=(0,g.ke)(b,function(a){return!a.uuid});
return $la(a,b)},t6=function(a,b){Hla((0,g.E)(a.g,C4));
b&&Q4()},v6=function(a,b){g.O.call(this);
this.C=b;var c=g.Zt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Ta(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;u6("Initialized with "+g.Sg(this.g))},w6=function(a,b,c){var d=d6(a.B,"/pairing/get_screen_availability");
e6(a.B,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},x6=function(a,b){a:if(g.ac(b)!=g.ac(a.g))var c=!1;
else{c=g.dc(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(u6("Updated online screens: "+g.Sg(a.g)),a.g=b,a.P("screenChange"));bma(a)},y6=function(a){(0,window.isNaN)(a.o)||g.ir(a.o);
a.o=g.gr((0,g.A)(a.Gr,a),0<a.A&&a.A<(0,g.D)()?2E4:1E4)},u6=function(a){j6("OnlineScreenService",a)},z6=function(a){var b={};
(0,g.C)(a.C(),function(a){a.token?b[a.token]=a.id:this.Eb("Requesting availability of screen w/o lounge token.")});
return b},bma=function(a){a=g.dc(g.Yb(a.g,function(a){return a}));
g.lb(a);a.length?g.Yt("yt-remote-online-screen-ids",a.join(","),60):g.$t("yt-remote-online-screen-ids")},A6=function(a){n6.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};cma(this)},C6=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.Id();if(k=(c?I4(k,c):null)||I4(k,b)){k.uuid=b;var l=B6(a,k);w6(a.l,l,function(a){e(a?l:null)})}else c?dma(a,c,(0,g.A)(function(a){var f=B6(this,new A4({name:d,
screenId:c,loungeToken:a,dialId:b||""}));w6(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},D6=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},dma=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={jb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.yr(d6(a.C,"/pairing/get_lounge_token_batch"),e)},E6=function(a){a.g=a.o.Id();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+F4(a.g))},cma=function(a){F6(a);
a.o=new r6(a.C);a.o.subscribe("screenChange",(0,g.A)(a.cD,a));E6(a);a.A=D4(g.Zt("yt-remote-automatic-screen-cache")||[]);F6(a);a.info("Initializing automatic screens: "+F4(a.A));a.l=new v6(a.C,(0,g.A)(a.Id,a,!0));a.l.subscribe("screenChange",(0,g.A)(function(){this.P("onlineScreenChange")},a))},B6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=I4(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.Yt("yt-remote-automatic-screen-cache",(0,g.E)(a.A,C4)));F6(a);a.B[b.uuid]=b.id;g.Yt("yt-remote-device-id-map",a.B,31536E3);return b},F6=function(a){a.B=g.Zt("yt-remote-device-id-map")||{}},G6=function(a,b,c){g.O.call(this);
this.T=c;this.H=a;this.l=b;this.o=null},H6=function(a,b){j6(a.T,b)},J6=function(a,b){G6.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.A)(this.YM,this);this.B=(0,g.A)(this.FL,this);this.A=g.gr((0,g.A)(function(){I6(this,null)},this),12E4)},ema=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Sg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.xa,(0,g.A)(function(){H6(this,"Failed to send message: getMdxSessionStatus.")},a)):H6(a,"Sending yt message without session: "+g.Sg(b))},I6=function(a,b){g.ir(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.A)(a.dn,a),d=(0,g.A)(a.Md,a);a.Cu(b,c,d,5)}}else a.Md(Error("Waiting for session status timed out."))},K6=function(a,b,c){G6.call(this,a,b,"DialSession");
this.A=this.G=null;this.J="";this.R=c;this.B=null;this.F=g.xa;this.C=window.NaN;this.N=(0,g.A)(this.bN,this);this.g=g.xa},L6=function(a){a.g=a.H.AA(a.J,a.l.label,a.l.friendlyName,(0,g.A)(function(a){this.g=g.xa;
this.dn(a)},a),(0,g.A)(function(a){this.g=g.xa;
this.Md(a)},a))},M6=function(a){var b={};
b.pairingCode=a.J;b.theme=a.R;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}T4()&&(b.env_useStageMdx=1);return g.jh(b)},N6=function(a,b){G6.call(this,a,b,"ManualSession");
this.g=g.gr((0,g.A)(this.Ai,this,null),150)},O6=function(a,b,c,d){g.O.call(this);
this.l=a;this.F=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.A)(this.pK,this)},P6=function(a,b){return b?g.Pa(a.o,function(a){return B4(b,a.label)},a):null},Q6=function(a){j6("Controller",a)},f6=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},R6=function(a){return a.B||!!a.o.length||!!a.g},S6=function(a,b,c){b!=a.g&&(g.lf(a.g),(a.g=b)?(c?a.P("yt-remote-cast2-receiver-resumed",b.l):a.P("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.A)(a.ry,a,b)),b.o?a.P("yt-remote-cast2-session-change",b.o):c&&a.g.Ai(null)):a.P("yt-remote-cast2-session-change",null))},T6=function(a){var b=a.l.zA(),c=a.g&&a.g.l;
a=(0,g.E)(b,function(a){c&&B4(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=P6(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},jma=function(a,b,c,d,e,f,k){fma()?gma(b,e,f,k)&&(V6(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?W6(a,c):(window.__onGCastApiAvailable=function(b,d){b?W6(a,c):(X6("Failed to load cast API: "+d),Y6(!1),V6(!1),g.$t("yt-remote-cast-available"),g.$t("yt-remote-cast-receiver"),Z6(),c(!1))},
d?Mla():$4("CriOS")?Pla():$4("Android")&&$4("Chrome/")&&window.navigator.presentation?Qla():window.chrome&&window.navigator.presentation&&!$4("Edge")?(a5(),X4(hma.map(Nla))):Y4())):U6("Cannot initialize because not running Chrome")},Z6=function(){U6("dispose");
var a=$6();a&&a.dispose();g.y("yt.mdx.remote.cloudview.instance_",null,void 0);a7(!1);g.Zs(b7);b7.length=0},c7=function(){return!!g.Zt("yt-remote-cast-installed")},d7=function(){var a=g.Zt("yt-remote-cast-receiver");
return a?a.friendlyName:null},e7=function(){U6("clearCurrentReceiver");
g.$t("yt-remote-cast-receiver")},f7=function(){return c7()?$6()?$6().getCastSession():(X6("getCastSelector: Cast is not initialized."),null):(X6("getCastSelector: Cast API is not installed!"),null)},h7=function(){c7()?$6()?g7()?(U6("Requesting cast selector."),$6().requestSession()):(U6("Wait for cast API to be ready to request the session."),b7.push(g.Ys("yt-remote-cast2-api-ready",h7))):X6("requestCastSelector: Cast is not initialized."):X6("requestCastSelector: Cast API is not installed!")},i7=
function(a,b){g7()?$6().setConnectedScreenStatus(a,b):X6("setConnectedScreenStatus called before ready.")},fma=function(){var a=0<=g.Vb.search(/ (CrMo|Chrome|CriOS)\//);
return g.pv||a},kma=function(a,b){$6().init(a,b)},gma=function(a,b,c,d){var e=!1;
$6()||(a=new O6(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.Yt("yt-remote-cast-available",a);g.bt("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){U6("onReceiverSelected: "+a.friendlyName);
g.Yt("yt-remote-cast-receiver",a);g.bt("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){U6("onReceiverResumed: "+a.friendlyName);
g.Yt("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){U6("onSessionChange: "+E4(a));
a||g.$t("yt-remote-cast-receiver");g.bt("yt-remote-cast2-session-change",a)}),g.y("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
U6("cloudview.createSingleton_: "+e);return e},$6=function(){return g.z("yt.mdx.remote.cloudview.instance_")},W6=function(a,b){Y6(!0);
V6(!1);kma(a,function(a){a?(a7(!0),g.at("yt-remote-cast2-api-ready")):(X6("Failed to initialize cast API."),Y6(!1),g.$t("yt-remote-cast-available"),g.$t("yt-remote-cast-receiver"),Z6());b(a)})},U6=function(a){j6("cloudview",a)},X6=function(a){j6("cloudview",a)},Y6=function(a){U6("setCastInstalled_ "+a);
g.Yt("yt-remote-cast-installed",a)},g7=function(){return!!g.z("yt.mdx.remote.cloudview.apiReady_")},a7=function(a){U6("setApiReady_ "+a);
g.y("yt.mdx.remote.cloudview.apiReady_",a,void 0)},V6=function(a){g.y("yt.mdx.remote.cloudview.initializing_",a,void 0)},j7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.l=null;this.hasNext=this.Te=!1;this.J=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},k7=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Te=!1;a.hasNext=!1;a.G=0;a.F=(0,g.D)();a.B=0;a.o=0;a.H=0;a.J=0;a.A=window.NaN;a.C=!1},l7=function(a){return 1==a.g?((0,g.D)()-a.F)/1E3:0},m7=function(a,b){a.G=b;
a.F=(0,g.D)()},n7=function(a){switch(a.g){case 1:case 1081:return((0,g.D)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},o7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&k7(a)},p7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.pc(a.l);b.hasPrevious=a.Te;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.J;b.liveIngestionTime=a.A;return b},s7=function(a,b){g.O.call(this);
this.g=0;this.A=a;this.C=[];this.B=new x4;this.o=this.l=null;this.H=(0,g.A)(this.eI,this);this.F=(0,g.A)(this.Dk,this);this.G=(0,g.A)(this.dI,this);this.J=(0,g.A)(this.qI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.ys,this),q7(this))):c=3;0!=c&&(b?this.ys(c):g.gr((0,g.A)(function(){this.ys(c)},this),0));
var d=f7();d&&r7(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},t7=function(a){return new j7(a.A.getPlayerContextData())},q7=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Ja(this.lK,a),this))},a)},u7=function(a){(0,g.C)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},v7=function(a,b){var c=a.B;
50>c.g.length+c.l.length&&a.B.l.push(b)},x7=function(a,b,c){var d=t7(a);
m7(d,c);-1E3!=d.g&&(d.g=b);w7(a,d)},y7=function(a,b,c){a.A.sendMessage(b,c)},w7=function(a,b){u7(a);
a.A.setPlayerContextData(p7(b));q7(a)},r7=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.F),a.Dk(null));
a.o=b;a.o&&(j6("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.F),a.o.media.length&&a.Dk(a.o.media[0]))},z7=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=t7(a);b.contentId!=d.videoId&&j6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;m7(d,a.l.getEstimatedTime());w7(a,d)}else j6("CP","No cast media video. Ignoring state update.")},A7=function(a,b,c){return(0,g.A)(function(a){this.Eb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Eb("Retrying "+b+" using MDx browser channel."),y7(this,b,c))},a)},B7=function(a,b,c){g.O.call(this);
this.B=window.NaN;this.R=!1;this.J=this.H=this.N=this.T=window.NaN;this.U=[];this.A=this.F=this.o=this.Na=this.g=null;this.ra=a;this.U.push(g.xs(window,"beforeunload",(0,g.A)(this.JC,this)));this.l=[];this.Na=new j7;this.Z=b.id;this.g=lma(this,c);this.g.subscribe("handlerOpened",this.iI,this);this.g.subscribe("handlerClosed",this.fI,this);this.g.subscribe("handlerError",this.gI,this);this.g.subscribe("handlerMessage",this.hI,this);Vla(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Na.videoId;g.au()&&g.Yt("yt-remote-session-video-id",a)},this)},C7=function(a){j6("conn",a)},lma=function(a,b){return new $5(d6(a.ra,"/bc"),b)},D7=function(a,b){a.P("proxyStateChange",b)},mma=function(a){a.B=g.gr((0,g.A)(function(){C7("Connecting timeout");
this.C(1)},a),2E4)},E7=function(a){g.ir(a.B);
a.B=window.NaN},F7=function(a){g.ir(a.T);
a.T=window.NaN},nma=function(a){G7(a);
a.N=g.gr((0,g.A)(function(){H7(this,"getNowPlaying")},a),2E4)},G7=function(a){g.ir(a.N);
a.N=window.NaN},J7=function(a,b){b&&(E7(a),F7(a));
b==(b6(a.g)&&(0,window.isNaN)(a.B))?b&&(D7(a,1),H7(a,"getSubtitlesTrack")):b?(a.ba()&&a.Na.reset(),D7(a,1),H7(a,"getNowPlaying"),I7(a)):a.C(1)},oma=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Na.videoId&&(g.jc(b.params)?a.Na.l=null:a.Na.l=b.params,a.P("remotePlayerChange"))},K7=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Na.listId=b.params.listId||a.Na.listId;o7(a.Na,c,d);a.P("remoteQueueChange")},pma=function(a,b){b.params=b.params||{};
K7(a,b);L7(a,b);a.P("autoplayDismissed")},L7=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
m7(a.Na,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Na.g&&(c=-1E3);a.Na.g=c;c=Number(b.params.loadedTime);a.Na.J=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Na.H=(0,window.isNaN)(c)?0:c;c=a.Na;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Na;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Na.g?nma(a):G7(a);
a.P("remotePlayerChange")},qma=function(a,b){if(-1E3!=a.Na.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Na.g=c;c=(0,window.parseInt)(b.params.currentTime,10);m7(a.Na,(0,window.isNaN)(c)?0:c);a.P("remotePlayerChange")}},rma=function(a,b){var c="true"==b.params.muted;
a.Na.volume=(0,window.parseInt)(b.params.volume,10);a.Na.muted=c;a.P("remotePlayerChange")},sma=function(a,b){a.F=b.params.videoId;
a.P("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},tma=function(a,b){var c="true"==b.params.hasNext;
a.Na.Te="true"==b.params.hasPrevious;a.Na.hasNext=c;a.P("previousNextChange")},I7=function(a){g.ir(a.J);
a.J=g.gr((0,g.A)(a.C,a,1),864E5)},H7=function(a,b,c){c?C7("Sending: action="+b+", params="+g.Sg(c)):C7("Sending: action="+b);
a.g.sendMessage(b,c)},M7=function(a){n6.call(this,"ScreenServiceProxy");
this.Cc=a;this.l=[];this.l.push(this.Cc.$_s("screenChange",(0,g.A)(this.WM,this)));this.l.push(this.Cc.$_s("onlineScreenChange",(0,g.A)(this.PJ,this)))},yma=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.br("MDX_CONFIG")||b;Fla();N4();N7||(N7=new c6(b?b.loungeApiHost:void 0),T4()&&(N7.g="/api/loungedev"));O7||(O7=g.z("yt.mdx.remote.deferredProxies_")||[],g.y("yt.mdx.remote.deferredProxies_",O7,void 0));uma();var c=P7();if(!c){var d=new A6(N7);g.y("yt.mdx.remote.screenService_",d,void 0);c=P7();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);jma(a,d,function(a){a?Q7()&&i7(Q7(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.bt("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.z("yt.mdx.remote.initialized_")&&(g.y("yt.mdx.remote.initialized_",!0,void 0),R7("Initializing: "+g.Sg(b)),S7.push(g.Ys("yt-remote-cast2-availability-change",function(){g.bt("yt-remote-receiver-availability-change")})),S7.push(g.Ys("yt-remote-cast2-receiver-selected",function(){T7(null);
g.bt("yt-remote-auto-connect","cast-selector-receiver")})),S7.push(g.Ys("yt-remote-cast2-receiver-resumed",function(){g.bt("yt-remote-receiver-resumed","cast-selector-receiver")})),S7.push(g.Ys("yt-remote-cast2-session-change",vma)),S7.push(g.Ys("yt-remote-connection-change",function(a){a?i7(Q7(),"YouTube TV"):U7()||(i7(null,null),e7())})),a=V7(),b.isAuto&&(a.id+="#dial"),g.Ss("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),R7(" -- with channel params: "+
g.Sg(a)),wma(a),c.start(),Q7()||xma())},zma=function(){var a=W7();
c7()&&g.Zt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},W7=function(){var a=P7().Cc.$_gos();
var b=X7();b&&Y7()&&(H4(a,b)||a.push(b));return Ela(a)},Z7=function(){var a=Ama();
!a&&c7()&&d7()&&(a={key:"cast-selector-receiver",name:d7()});return a},Ama=function(){var a=W7(),b=X7();
b||(b=U7());return g.Pa(a,function(a){return b&&B4(b,a.key)?!0:!1})},X7=function(){var a=Q7();
if(!a)return null;var b=P7().Id();return I4(b,a)},vma=function(a){R7("remote.onCastSessionChange_: "+E4(a));
if(a){var b=X7();b&&b.id==a.id?i7(b.id,"YouTube TV"):(b&&$7(),a8(a,1))}else Y7()&&$7()},$7=function(){g7()?$6().stopSession():X6("stopSession called before API ready.");
var a=Y7();a&&(a.disconnect(1),b8(null))},c8=function(){var a=Y7();
return!!a&&3!=a.getProxyState()},R7=function(a){j6("remote",a)},P7=function(){if(!d8){var a=g.z("yt.mdx.remote.screenService_");
d8=a?new M7(a):null}return d8},Q7=function(){return g.z("yt.mdx.remote.currentScreenId_")},e8=function(a){g.y("yt.mdx.remote.currentScreenId_",a,void 0)},f8=function(){return g.z("yt.mdx.remote.connectData_")},T7=function(a){g.y("yt.mdx.remote.connectData_",a,void 0)},Y7=function(){return g.z("yt.mdx.remote.connection_")},b8=function(a){var b=Y7();
T7(null);a||e8("");g.y("yt.mdx.remote.connection_",a,void 0);O7&&((0,g.C)(O7,function(b){b(a)}),O7.length=0);
b&&!a?g.bt("yt-remote-connection-change",!1):!b&&a&&g.bt("yt-remote-connection-change",!0)},U7=function(){var a=g.au();
if(!a)return null;var b=P7().Id();return I4(b,a)},a8=function(a,b){X7()&&X7();
e8(a.id);var c=new B7(N7,a,V7());c.connect(b,f8());c.subscribe("beforeDisconnect",function(a){g.bt("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){Y7()&&b8(null)});
b8(c)},xma=function(){var a=U7();
a?(R7("Resume connection to: "+E4(a)),a8(a,0)):(R4(),e7(),R7("Skipping connecting because no session screen found."))},uma=function(){var a=V7();
if(g.jc(a)){a=M4();var b=g.Zt("yt-remote-session-name")||"",c=g.Zt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.y("yt.mdx.remote.channelParams_",a,void 0)}},V7=function(){return g.z("yt.mdx.remote.channelParams_")||{}},wma=function(a){a?(g.Yt("yt-remote-session-app",a.app),g.Yt("yt-remote-session-name",a.name)):(g.$t("yt-remote-session-app"),g.$t("yt-remote-session-name"));
g.y("yt.mdx.remote.channelParams_",a,void 0)},g8=function(a,b,c){g.H.call(this);
this.A=a;this.L=b;this.l=new g.Ks(this);g.I(this,this.l);this.l.M(b,"onCaptionsTrackListChanged",this.hJ);this.l.M(b,"captionschanged",this.cI);this.l.M(b,"captionssettingschanged",this.Nz);this.l.M(b,"videoplayerreset",this.fn);this.l.M(b,"mdxautoplaycancel",this.aC);this.R=this.l.M(b,"onVolumeChange",this.Zx);this.F=!1;this.g=c;c.subscribe("proxyStateChange",this.my,this);c.subscribe("remotePlayerChange",this.Fk,this);c.subscribe("remoteQueueChange",this.fn,this);c.subscribe("autoplayUpNext",this.Lx,
this);c.subscribe("previousNextChange",this.jy,this);c.subscribe("nowAutoplaying",this.ey,this);c.subscribe("autoplayDismissed",this.Kx,this);this.suggestion=null;this.G=new g.MC(64);this.o=new g.M(this.Kz,500,this);g.I(this,this.o);this.B=new g.M(this.Lz,1E3,this);g.I(this,this.B);this.J=new b5(this.CM,0,this);g.I(this,this.J);this.C={};this.N=new g.M(this.lA,1E3,this);g.I(this,this.N);this.H=new g.Lm(this.gG,1E3,this);g.I(this,this.H);this.T=g.xa;this.Nz();this.fn();this.Fk()},h8=function(a,b){a.A.od(b,
a.L.getVideoData().lengthSeconds)},j8=function(a){h8(a,0);
a.o.stop();i8(a,new g.MC(64))},l8=function(a,b){if(k8(a)&&!a.F){var c=null;
b&&(c={style:a.L.Bh()},g.rc(c,b));a.g.Bz(a.L.getVideoData(1).videoId,c);a.C=t7(a.g).l}},m8=function(a,b){var c=a.L.We();
if(c){var d=c.Ra;var e=c.listId.toString()}var f=a.L.getVideoData(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;var m=f.ri;f=w4(f);var n=t7(c);l=l||0;var p={videoId:k,currentIndex:l};o7(n,k,l);g.t(b)&&(m7(n,b),p.currentTime=b);g.t(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.Sg(f));y7(c,"setPlaylist",p);e||w7(c,n);i8(a,new g.MC(1))},n8=function(a,b){if(b){var c=a.L.Vb("captions","tracklist",{ev:1});
c&&c.length?(a.L.gd("captions","track",b),a.F=!1):(a.L.Hi("captions"),a.F=!0)}else a.L.gd("captions","track",{})},k8=function(a){return t7(a.g).videoId==a.L.getVideoData(1).videoId},i8=function(a,b){a.B.stop();
var c=a.G;if(!g.RC(c,b)){var d=g.U(b,2);d!=g.U(a.G,2)&&g.hJ(a.L,d);a.G=b;o8(a.A,c,b)}},q8=function(a){g.Q.call(this,{D:"div",
I:"ytp-remote",K:[{D:"div",I:"ytp-remote-display-status",K:[{D:"div",I:"ytp-remote-display-status-icon",K:[g.RN()]},{D:"div",I:"ytp-remote-display-status-text",W:"{{statustext}}"}]}]});this.l=new g.wO(this,250);g.I(this,this.l);this.o=a;this.M(a,"presentingplayerstatechange",this.A);p8(this,g.dJ(a))},p8=function(a,b){if(3==a.o.Da()){var c={RECEIVER_NAME:a.o.Vb("remote","currentReceiver").name};
c=g.U(b,128)?g.xQ("Error on $RECEIVER_NAME",c):g.SC(b)||g.U(b,4)?g.xQ("Playing on $RECEIVER_NAME",c):g.xQ("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},r8=function(a,b){g.fS.call(this,"Play on",0,a,b);
this.L=a;this.F={};this.M(a,"onMdxReceiversChange",this.H);this.M(a,"presentingplayerstatechange",this.H);this.H()},s8=function(a){g.LJ.call(this,a);
this.o={key:G4(),name:"This computer"};this.B=null;this.C=[];this.J=this.l=null;this.H=[this.o];this.A=this.o;this.F=new g.MC(64);this.N=0;this.G=-1;if(!g.Uz(g.V(this.g))){a=this.g;var b=g.Ru(a);b&&(b=b.Qm())&&(b=new r8(a,b),g.I(this,b));b=new q8(a);g.I(this,b);g.yJ(a,b.element,4)}},o8=function(a,b,c){a.F=c;
a.g.P("presentingplayerstatechange",new g.XC(c,b))},t8=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)$7();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.getVideoData(1);var e=d.videoId;if(c||e){var f=a.g.We();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.xb(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.ri,index:Math.max(a.g.jw(),0),currentTime:0==f?void 0:f};(d=w4(d))&&(c.locationInfo=d);d=c}else d=null;R7("Connecting to: "+g.Sg(b));"cast-selector-receiver"==b.key?(T7(d||null),g7()?$6().setLaunchParams(d||null):
X6("setLaunchParams called before ready.")):!d&&c8()&&Q7()==b.key?g.bt("yt-remote-connection-change",!0):($7(),T7(d||null),d=P7().Id(),(d=I4(d,b.key))&&a8(d,1))}},vla=/^https?$/i,Bma=["POST",
"PUT"];g.B(u4,g.Qf);g.h=u4.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.H+"; newUri="+a);b=b?b.toUpperCase():"GET";this.H=a;this.B="";this.A=0;this.Y=b;this.U=!1;this.l=!0;this.g=this.R?m4(this.R):m4(g.LW);this.T=this.R?l4(this.R):l4(g.LW);this.g.onreadystatechange=(0,g.A)(this.Mu,this);try{h4(n4(this,"Opening Xhr")),this.Z=!0,this.g.open(b,String(a),!0),this.Z=!1}catch(f){h4(n4(this,"Error opening Xhr: "+f.message));r4(this,f);return}a=c||"";var e=this.headers.clone();
d&&sla(d,function(a,b){e.set(b,a)});
d=g.Pa(e.Gd(),tla);c=g.w.FormData&&a instanceof g.w.FormData;!g.Ta(Bma,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.g.setRequestHeader(b,a)},this);
this.ga&&(this.g.responseType=this.ga);"withCredentials"in this.g&&this.g.withCredentials!==this.ba&&(this.g.withCredentials=this.ba);try{o4(this),0<this.C&&(this.N=ula(this.g),h4(n4(this,"Will abort after "+this.C+"ms if incomplete, xhr2 "+this.N)),this.N?(this.g.timeout=this.C,this.g.ontimeout=(0,g.A)(this.Nu,this)):this.F=g.Ig(this.Nu,this.C,this)),h4(n4(this,"Sending request")),this.G=!0,this.g.send(a),this.G=!1}catch(f){h4(n4(this,"Send error: "+f.message)),r4(this,f)}};
g.h.Nu=function(){"undefined"!=typeof g.oW&&this.g&&(this.B="Timed out after "+this.C+"ms, aborting",this.A=8,n4(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.l&&(n4(this,"Aborting"),this.l=!1,this.o=!0,this.g.abort(),this.o=!1,this.A=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),q4(this))};
g.h.V=function(){this.g&&(this.l&&(this.l=!1,this.o=!0,this.g.abort(),this.o=!1),q4(this,!0));u4.ya.V.call(this)};
g.h.Mu=function(){this.fa()||(this.Z||this.G||this.o?t4(this):this.oK())};
g.h.oK=function(){t4(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<s4(this)?this.g.status:-1}catch(a){return-1}};
var q5={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},p5={"'":"\\'"},Cma={};g.h=x4.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.l.length};
g.h.clear=function(){this.g=[];this.l=[]};
g.h.contains=function(a){return g.Ta(this.g,a)||g.Ta(this.l,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.rha)(b,a);0<=c?(g.Wa(b,c),b=!0):b=!1;return b||g.Xa(this.l,a)};
g.h.wc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};
var Cla={lN:"atp",xP:"ska",mP:"que",MO:"mus",wP:"sus",cO:"dsp"};z4.prototype.El=function(){var a=new z4({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var S4,L4="",Z4=U4("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",Ola=U4("loadCastFramework")||U4("loadCastApplicationFramework"),hma=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(b5,g.H);g.h=b5.prototype;g.h.EC=function(a){this.A=arguments;this.g=!1;this.Ca?this.o=(0,g.D)()+this.Sc:this.Ca=g.Ig(this.B,this.Sc)};
g.h.stop=function(){this.Ca&&(g.w.clearTimeout(this.Ca),this.Ca=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.V=function(){this.stop();b5.ya.V.call(this)};
g.h.FC=function(){this.o?(this.Ca=g.Ig(this.B,this.o-(0,g.D)()),this.o=null):(this.Ca=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};c5.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
c5.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=d5.prototype;g.h.jh=null;g.h.Ce=!1;g.h.fj=null;g.h.ws=null;g.h.Ui=null;g.h.oi=null;g.h.ug=null;g.h.Kg=null;g.h.Eh=null;g.h.sc=null;g.h.Yk=0;g.h.Ee=null;g.h.co=null;g.h.vg=null;g.h.Wj=-1;g.h.nz=!0;g.h.Zg=!1;g.h.vp=0;g.h.vn=null;var k5={},i5={};g.h=d5.prototype;g.h.setTimeout=function(a){this.A=a};
g.h.PL=function(a){a=a.target;var b=this.vn;b&&3==s4(a)?b.Rj():this.uA(a)};
g.h.uA=function(a){try{if(a==this.sc)a:{var b=s4(this.sc),c=this.sc.A,d=this.sc.getStatus();if(g.Vd&&!g.Fc(10)||g.Xd&&!g.Dc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Uh&&!v4(this.sc))break a;this.Zg||4!=b||7==c||(8==c||0>=d?this.g.ye(3):this.g.ye(2));u5(this);var e=this.sc.getStatus();this.Wj=e;var f=v4(this.sc);(this.Ce=200==e)?(4==b&&m5(this),this.B?(o5(this,b,f),g.Uh&&this.Ce&&3==b&&(this.ca.ea(this.l,"tick",this.LL),this.l.start())):l5(this,f),this.Ce&&!this.Zg&&(4==b?this.g.cn(this):(this.Ce=
!1,h5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.vg=3,j5(13)):(this.vg=0,j5(14)),m5(this),n5(this))}}catch(k){this.sc&&v4(this.sc)}finally{}};
g.h.LL=function(){var a=s4(this.sc),b=v4(this.sc);this.Yk<b.length&&(u5(this),o5(this,a,b),this.Ce&&4!=a&&h5(this))};
g.h.jL=function(a){t5((0,g.A)(this.iL,this,a),0)};
g.h.iL=function(a){this.Zg||(u5(this),l5(this,a),h5(this))};
g.h.yy=function(a){t5((0,g.A)(this.hL,this,a),0)};
g.h.hL=function(a){this.Zg||(m5(this),this.Ce=a,this.g.cn(this),this.g.ye(4))};
g.h.cancel=function(){this.Zg=!0;m5(this)};
g.h.uL=function(){this.fj=null;var a=(0,g.D)();0<=a-this.ws?(2!=this.oi&&this.g.ye(3),m5(this),this.vg=2,j5(18),n5(this)):s5(this,this.ws-a)};g.h=y5.prototype;g.h.tp=null;g.h.Od=null;g.h.wn=!1;g.h.Lu=null;g.h.Rl=null;g.h.Wp=null;g.h.up=null;g.h.Xd=null;g.h.yf=-1;g.h.Vj=null;g.h.nj=null;g.h.connect=function(a){this.up=a;a=z5(this.g,null,this.up);j5(3);this.Lu=(0,g.D)();var b=this.g.G;null!=b?(this.Vj=b[0],(this.nj=b[1])?(this.Xd=1,A5(this)):(this.Xd=2,C5(this))):(j4(a,"MODE","init"),this.Od=new d5(this,void 0,void 0,void 0),this.Od.jh=this.tp,g5(this.Od,a,!1,null,!0),this.Xd=0)};
g.h.bC=function(a){if(a)this.Xd=2,C5(this);else{j5(4);var b=this.g;b.Re=b.kg.yf;W5(b,9)}a&&this.ye(2)};
g.h.Mo=function(a){return this.g.Mo(a)};
g.h.abort=function(){this.Od&&(this.Od.cancel(),this.Od=null);this.yf=-1};
g.h.Ku=function(){return!1};
g.h.ny=function(a,b){this.yf=a.Wj;if(0==this.Xd)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.Re=this.yf;W5(c,2);return}this.Vj=c[0];this.nj=c[1]}else c=this.g,c.Re=this.yf,W5(c,2);else if(2==this.Xd)if(this.wn)j5(7),this.Wp=(0,g.D)();else if("11111"==b){if(j5(6),this.wn=!0,this.Rl=(0,g.D)(),c=this.Rl-this.Lu,!g.Vd||g.Fc(10)||500>c)this.yf=200,this.Od.cancel(),j5(12),B5(this.g,this,!0)}else j5(8),this.Rl=this.Wp=(0,g.D)(),this.wn=!1};
g.h.cn=function(){this.yf=this.Od.Wj;if(this.Od.Ce)0==this.Xd?this.nj?(this.Xd=1,A5(this)):(this.Xd=2,C5(this)):2==this.Xd&&((!g.Vd||g.Fc(10)?!this.wn:200>this.Wp-this.Rl)?(j5(11),B5(this.g,this,!1)):(j5(12),B5(this.g,this,!0)));else{0==this.Xd?j5(9):2==this.Xd&&j5(10);var a=this.g;a.Re=this.yf;W5(a,2)}};
g.h.Pk=function(){return this.g.Pk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.ye=function(a){this.g.ye(a)};g.h=D5.prototype;g.h.Dj=null;g.h.ud=null;g.h.Sb=null;g.h.rp=null;g.h.Vl=null;g.h.Bt=null;g.h.hm=null;g.h.Bk=0;g.h.vH=0;g.h.Qc=null;g.h.pg=null;g.h.mf=null;g.h.eh=null;g.h.kg=null;g.h.ao=null;g.h.zi=-1;g.h.Cv=-1;g.h.Re=-1;g.h.ii=0;g.h.bi=0;g.h.ah=8;var X5=new g.Qf;g.B(E5,g.nf);g.B(F5,g.nf);g.B(G5,g.nf);g.h=D5.prototype;g.h.connect=function(a,b,c,d,e){j5(0);this.rp=b;this.Dj=c||{};d&&g.t(e)&&(this.Dj.OSID=d,this.Dj.OAID=e);this.C?(t5((0,g.A)(this.Ut,this,a),100),M5(this)):this.Ut(a)};
g.h.Ut=function(a){this.kg=new y5(this);this.kg.tp=null;this.kg.l=this.B;this.kg.connect(a)};
g.h.Ku=function(){return 0==this.g};
g.h.vy=function(a){this.pg=null;R5(this,a)};
g.h.ty=function(){this.mf=null;this.Sb=new d5(this,this.o,"rpc",this.F);this.Sb.jh=null;this.Sb.vp=0;var a=this.Bt.clone();g.Wo(a,"RID","rpc");g.Wo(a,"SID",this.o);g.Wo(a,"CI",this.ao?"0":"1");g.Wo(a,"AID",this.zi);I5(this,a);if(!g.Vd||g.Fc(10))g.Wo(a,"TYPE","xmlhttp"),g5(this.Sb,a,!0,this.hm,!1);else{g.Wo(a,"TYPE","html");var b=this.Sb,c=!!this.hm;b.oi=3;b.ug=i4(a.clone());r5(b,c)}};
g.h.ny=function(a,b){if(0!=this.g&&(this.Sb==a||this.ud==a))if(this.Re=a.Wj,this.ud==a&&3==this.g)if(7<this.ah){try{var c=this.B.parse(b)}catch(f){c=null}if(g.Aa(c)&&3==c.length)if(0==c[0])a:{if(!this.mf){if(this.Sb)if(this.Sb.Ui+3E3<this.ud.Ui)N5(this),this.Sb.cancel(),this.Sb=null;else break a;U5(this);j5(19)}}else this.Cv=c[1],0<this.Cv-this.zi&&37500>c[2]&&this.ao&&0==this.bi&&!this.eh&&(this.eh=t5((0,g.A)(this.YH,this),6E3));else W5(this,11)}else b!=Cma.LN.g&&W5(this,11);else if(this.Sb==a&&
N5(this),!g.vb(b)){c=this.B.parse(b);g.Aa(c);for(var d=0;d<c.length;d++){var e=c[d];this.zi=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.hm=e[2],e=e[3],null!=e?this.ah=e:this.ah=6,this.g=3,this.Qc&&this.Qc.Jt(),this.Bt=z5(this,this.Pk()?this.hm:null,this.rp),S5(this)):"stop"==e[0]&&W5(this,7):3==this.g&&("stop"==e[0]?W5(this,7):"noop"!=e[0]&&this.Qc&&this.Qc.It(e),this.bi=0)}}};
g.h.YH=function(){null!=this.eh&&(this.eh=null,this.Sb.cancel(),this.Sb=null,U5(this),j5(20))};
g.h.cn=function(a){if(this.Sb==a){N5(this);this.Sb=null;var b=2}else if(this.ud==a)this.ud=null,b=1;else return;this.Re=a.Wj;if(0!=this.g)if(a.Ce)1==b?(b=(0,g.D)()-a.Ui,X5.dispatchEvent(new F5(X5,a.Eh?a.Eh.length:0,b,this.ii)),L5(this),this.A.length=0):S5(this);else{var c=a.vg,d;if(!(d=3==c||7==c||0==c&&0<this.Re)){if(d=1==b)this.ud||this.pg||1==this.g||2<=this.ii?d=!1:(this.pg=t5((0,g.A)(this.vy,this,a),T5(this,this.ii)),this.ii++,d=!0);d=!(d||2==b&&U5(this))}if(d)switch(c){case 1:W5(this,5);break;
case 4:W5(this,10);break;case 3:W5(this,6);break;case 7:W5(this,12);break;default:W5(this,2)}}};
g.h.pC=function(a){if(!g.Ta(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.pM=function(a){a?j5(2):(j5(1),V5(this,8))};
g.h.Mo=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new u4;a.ba=!1;return a};
g.h.isActive=function(){return!!this.Qc&&this.Qc.isActive(this)};
g.h.ye=function(a){X5.dispatchEvent(new G5(X5,a))};
g.h.Pk=function(){return!(!g.Vd||g.Fc(10))};
g.h=Y5.prototype;g.h.Jt=function(){};
g.h.It=function(){};
g.h.Ht=function(){};
g.h.Do=function(){};
g.h.vu=function(){return{}};
g.h.isActive=function(){return!0};g.B(Z5,g.H);g.h=Z5.prototype;g.h.cL=function(){this.Sc=Math.min(3E5,2*this.Sc);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.Sc+15E3*Math.random();g.$p(this.g,a);this.l=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Sc=5E3};g.B($5,Y5);g.h=$5.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Gc=function(a){return this.o.Gc(a)};
g.h.P=function(a,b){return this.o.P.apply(this.o,arguments)};
g.h.dispose=function(){this.J||(this.J=!0,g.lf(this.o),a6(this),g.lf(this.l),this.l=null)};
g.h.fa=function(){return this.J};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.N+"/test";b=this.N+"/bind";var d=new D5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.T),e=this.g;e&&(e.Qc=null);d.Qc=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.zi):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.rc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.F.push(c):b6(this)&&O5(this.g,c)};
g.h.Jt=function(){this.l.reset();this.B=null;this.A=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)O5(this.g,a[b])}this.P("handlerOpened")};
g.h.Ht=function(a){var b=2==a&&401==this.g.Re;4==a||b||this.l.start();this.P("handlerError",a)};
g.h.Do=function(a){if(!this.l.isActive())this.P("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.vu=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.rc(a,this.B);return a};
g.h.It=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),K5(this.g)):this.P("handlerMessage",new Tla(a[0],a[1]))};
g.h.SM=function(){this.l.isActive();var a=this.g,b=0;a.Sb&&b++;a.ud&&b++;0!=b||this.connect(this.B,this.A)};c6.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
c6.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
c6.prototype.B=function(a){a(Error("request timed out"))};var Zla=(0,g.D)(),h6=null,l6=Array(50),k6=-1,m6=!1;g.B(n6,g.O);n6.prototype.Id=function(){return this.g};
n6.prototype.contains=function(a){return!!H4(this.g,a)};
n6.prototype.get=function(a){return a?I4(this.g,a):null};
n6.prototype.info=function(a){j6(this.F,a)};g.B(p6,g.O);var u8=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=p6.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.Ca)&&this.yA()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.Ca)||(g.ir(this.Ca),this.Ca=window.NaN)};
g.h.V=function(){this.stop();p6.ya.V.call(this)};
g.h.yA=function(){this.Ca=window.NaN;this.g=g.yr(d6(this.C,"/pairing/get_screen"),{method:"POST",jb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.A)(this.UM,this),onError:(0,g.A)(this.TM,this),kd:(0,g.A)(this.VM,this)})};
g.h.UM=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.P("pairingComplete",new A4(c))};
g.h.TM=function(a){this.g=null;a.status&&404==a.status?this.l>=u8.length?this.P("pairingFailed",Error("DIAL polling timed out")):(a=u8[this.l],this.Ca=g.gr((0,g.A)(this.yA,this),a),this.l++):this.P("pairingFailed",Error("Server error "+a.status))};
g.h.VM=function(){this.g=null;this.P("pairingFailed",Error("Server not responding"))};g.B(r6,n6);g.h=r6.prototype;g.h.start=function(){q6(this)&&this.P("screenChange");!g.Zt("yt-remote-lounge-token-expiration")&&s6(this);g.ir(this.l);this.l=g.gr((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){q6(this);o6(this,a);t6(this,!1);this.P("screenChange");b(a);a.token||s6(this)};
g.h.remove=function(a,b){var c=q6(this);ama(this,a)&&(t6(this,!1),c=!0);b(a);c&&this.P("screenChange")};
g.h.Vn=function(a,b,c,d){var e=q6(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,t6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.P("screenChange")};
g.h.V=function(){g.ir(this.l);r6.ya.V.call(this)};
g.h.QC=function(a){q6(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}t6(this,!b);b&&j6(this.F,"Missed "+b+" lounge tokens.")};
g.h.PC=function(a){j6(this.F,"Requesting lounge tokens failed: "+a)};g.B(v6,g.O);g.h=v6.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.Zt("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.D)()-144E5<a?0:a)?y6(this):(this.A=(0,g.D)()+3E5,g.Yt("yt-remote-fast-check-period",this.A),this.Gr())};
g.h.isEmpty=function(){return g.jc(this.g)};
g.h.update=function(){u6("Updating availability on schedule.");var a=this.C(),b=g.Yb(this.g,function(b,d){return b&&!!I4(a,d)},this);
x6(this,b)};
g.h.V=function(){g.ir(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);v6.ya.V.call(this)};
g.h.Gr=function(){g.ir(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=z6(this);if(g.ac(a)){var b=d6(this.B,"/pairing/get_screen_availability");this.l=e6(this.B,b,{lounge_token:g.dc(a).join(",")},(0,g.A)(this.JK,this,a),(0,g.A)(this.IK,this))}else x6(this,{}),y6(this)};
g.h.JK=function(a,b){this.l=null;var c=g.dc(z6(this));if(g.pb(c,g.dc(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;x6(this,d);y6(this)}else this.Eb("Changing Screen set during request."),this.Gr()};
g.h.IK=function(a){this.Eb("Screen availability failed: "+a);this.l=null;y6(this)};
g.h.Eb=function(a){j6("OnlineScreenService",a)};g.B(A6,n6);g.h=A6.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.P("screenChange"),this.l.isEmpty()||this.P("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.Vn=function(a,b,c,d){this.o.contains(a)?this.o.Vn(a,b,c,d):(a="Updating name of unknown screen: "+a.name,j6(this.F,a),d(Error(a)))};
g.h.Id=function(a){return a?this.g:g.$a(this.g,(0,g.ke)(this.A,function(a){return!this.contains(a)},this))};
g.h.zA=function(){return(0,g.ke)(this.Id(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.AA=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new p6(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.lf(f);d(B6(this,a))},this));
f.subscribe("pairingFailed",function(a){g.lf(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.XM=function(a,b,c,d){g.yr(d6(this.C,"/pairing/get_screen"),{method:"POST",jb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new A4(d.screen||{});if(!e.name||D6(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);D6(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(B6(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
kd:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.lf(this.o);g.lf(this.l);A6.ya.V.call(this)};
g.h.cD=function(){E6(this);this.P("screenChange");this.l.update()};
A6.prototype.dispose=A6.prototype.dispose;g.B(G6,g.O);g.h=G6.prototype;g.h.dn=function(a){this.o=a;this.P("sessionScreen",this.o)};
g.h.Md=function(a){this.fa()||(a&&H6(this,""+a),this.o=null,this.P("sessionScreen",null))};
g.h.info=function(a){j6(this.T,a)};
g.h.CA=function(){return null};
g.h.Lr=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){H6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.Lr("");G6.ya.V.call(this)};g.B(J6,G6);g.h=J6.prototype;g.h.Kr=function(a){if(this.g){if(this.g==a)return;H6(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);ema(this)};
g.h.Ai=function(a){this.info("launchWithParams no-op for Cast: "+g.Sg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.A)(function(){this.Md()},this),(0,g.A)(function(){this.Md(Error("Failed to stop receiver app."))},this)):this.Md(Error("Stopping cast device witout session."))};
g.h.Lr=g.xa;g.h.V=function(){this.info("disposeInternal");g.ir(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;J6.ya.V.call(this)};
g.h.FL=function(a,b){if(!this.fa())if(b){var c=g.kq(b);if(g.Da(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Sg(c));switch(d){case "mdxSessionStatus":I6(this,c.screenId);break;default:H6(this,"Unknown youtube message: "+d)}}else H6(this,"Unable to parse message.")}else H6(this,"No data in message.")};
g.h.Cu=function(a,b,c,d){C6(this.H,this.l.label,a,this.l.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(H6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.gr((0,g.A)(this.Cu,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.CA=function(){return this.g};
g.h.YM=function(a){this.fa()||a||(H6(this,"Cast session died."),this.Md())};g.B(K6,G6);g.h=K6.prototype;g.h.Kr=function(a){this.A=a;this.A.addUpdateListener(this.N)};
g.h.Ai=function(a){this.B=a;this.F()};
g.h.stop=function(){this.g();this.g=g.xa;g.ir(this.C);this.A?this.A.stop((0,g.A)(this.Md,this,null),(0,g.A)(this.Md,this,"Failed to stop DIAL device.")):this.Md()};
g.h.V=function(){this.g();this.g=g.xa;g.ir(this.C);this.A&&this.A.removeUpdateListener(this.N);this.A=null;K6.ya.V.call(this)};
g.h.bN=function(a){this.fa()||a||(H6(this,"DIAL session died."),this.g(),this.g=g.xa,this.Md())};
g.h.Hp=function(a){this.J=G4();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,M6(this));a(b);L6(this)}else this.F=(0,g.A)(function(){g.ir(this.C);this.F=g.xa;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,M6(this));a(b);L6(this)},this),this.C=g.gr((0,g.A)(function(){this.F()},this),100)};
g.h.yD=function(a,b,c){C6(this.H,this.G.receiver.label,a,this.l.friendlyName,(0,g.A)(function(a){a&&a.token?(this.dn(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Hp(b,c)},this),(0,g.A)(function(a){H6(this,"Failed to get DIAL screen: "+a);
this.Hp(b,c)},this))};g.B(N6,G6);N6.prototype.stop=function(){this.Md()};
N6.prototype.Kr=g.xa;N6.prototype.Ai=function(){g.ir(this.g);this.g=window.NaN;var a=I4(this.H.Id(),this.l.label);a?this.dn(a):this.Md(Error("No such screen"))};
N6.prototype.V=function(){g.ir(this.g);this.g=window.NaN;N6.ya.V.call(this)};g.B(O6,g.O);g.h=O6.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.A)(this.qy,this),(0,g.A)(this.tK,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.zI,this);window.chrome.cast.initialize(c,
(0,g.A)(function(){this.fa()||(window.chrome.cast.addReceiverActionListener(this.A),Wla(),this.l.subscribe("onlineScreenChange",(0,g.A)(this.BA,this)),this.o=T6(this),window.chrome.cast.setCustomReceivers(this.o,g.xa,(0,g.A)(function(a){this.Eb("Failed to set initial custom receivers: "+g.Sg(a))},this)),this.P("yt-remote-cast2-availability-change",R6(this)),b(!0))},this),(0,g.A)(function(a){this.Eb("Failed to initialize API: "+g.Sg(a));
b(!1)},this))};
g.h.fM=function(a,b){Q6("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)Q6("Unsetting old screen status: "+this.g.l.friendlyName),S6(this,null)}if(a&&b){if(!this.g){c=I4(this.l.Id(),a);if(!c){Q6("setConnectedScreenStatus: Unknown screen.");return}var d=P6(this,c);d||(Q6("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.xa,(0,g.A)(function(a){this.Eb("Failed to set initial custom receivers: "+g.Sg(a))},this)));
Q6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);S6(this,new N6(this.l,d),!0)}this.g.Lr(b)}else Q6("setConnectedScreenStatus: no screen.")};
g.h.gM=function(a){this.fa()?this.Eb("Setting connection data on disposed cast v2"):this.g?this.g.Ai(a):this.Eb("Setting connection data without a session")};
g.h.aN=function(){this.fa()?this.Eb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),S6(this,null)):Q6("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.A)(this.qy,this),(0,g.A)(this.OK,this))};
g.h.V=function(){this.l.unsubscribe("onlineScreenChange",(0,g.A)(this.BA,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Xa(g.z("yt.mdx.remote.debug.handlers_")||[],f6);g.lf(this.g);O6.ya.V.call(this)};
g.h.Eb=function(a){j6("Controller",a)};
g.h.ry=function(a,b){this.g==a&&(b||S6(this,null),this.P("yt-remote-cast2-session-change",b))};
g.h.pK=function(a,b){if(!this.fa())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),Q6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)Q6("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{Q6("onReceiverAction_: Casting to active receiver.");this.g.o&&this.P("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:S6(this,
new N6(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:S6(this,new K6(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:S6(this,new J6(this.l,a));break;default:this.Eb("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.Eb("Stopping receiver w/o session: "+a.friendlyName)}else this.Eb("onReceiverAction_ called without receiver.")};
g.h.zI=function(a){if(this.fa())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.Eb("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.Eb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return Q6("Reselecting dial screen."),
this.P("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.Eb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);S6(this,new K6(this.l,b,this.C))}b=this.g;b.G=a;return b.G.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.A)(b.yD,b,(b.G.extraData||{}).screenId||null)):new window.Promise((0,g.A)(b.Hp,b))};
g.h.qy=function(a){if(!this.fa()){Q6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)Q6("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),S6(this,new J6(this.l,b),!0);else{this.Eb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=I4(this.l.Id(),c.label);
d&&B4(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(Q6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.lf(this.g),this.g=new J6(this.l,b),this.g.subscribe("sessionScreen",(0,g.A)(this.ry,this,this.g)),this.g.Ai(null));this.g.Kr(a)}}};
g.h.ZM=function(){return this.g?this.g.CA():null};
g.h.OK=function(a){this.fa()||(this.Eb("Failed to estabilish a session: "+g.Sg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&S6(this,null))};
g.h.tK=function(a){Q6("Receiver availability updated: "+a);if(!this.fa()){var b=R6(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;R6(this)!=b&&this.P("yt-remote-cast2-availability-change",R6(this))}};
g.h.BA=function(){this.fa()||(this.o=T6(this),Q6("Updating custom receivers: "+g.Sg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.xa,(0,g.A)(function(){this.Eb("Failed to set custom receivers.")},this)),this.P("yt-remote-cast2-availability-change",R6(this)))};
O6.prototype.setLaunchParams=O6.prototype.gM;O6.prototype.setConnectedScreenStatus=O6.prototype.fM;O6.prototype.stopSession=O6.prototype.aN;O6.prototype.getCastSession=O6.prototype.ZM;O6.prototype.requestSession=O6.prototype.requestSession;O6.prototype.init=O6.prototype.init;O6.prototype.dispose=O6.prototype.dispose;var b7=[];j7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";k7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Te=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.J=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
j7.prototype.isAdPlaying=function(){return 1081==this.g};
j7.prototype.clone=function(){return new j7(p7(this))};g.B(s7,g.O);g.h=s7.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.xa,A7(this,"play")):y7(this,"play"),x7(this,1,n7(t7(this))),this.P("remotePlayerChange")):v7(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.xa,A7(this,"pause")):y7(this,"pause"),x7(this,2,n7(t7(this))),this.P("remotePlayerChange")):v7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.l){var b=t7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.g||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.xa,A7(this,"seekTo",{newTime:a}))}else y7(this,"seekTo",{newTime:a});x7(this,3,a);this.P("remotePlayerChange")}else v7(this,g.Ja(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.xa,A7(this,"stopVideo")):y7(this,"stopVideo");var a=t7(this);a.index=-1;a.videoId="";k7(a);w7(this,a);this.P("remotePlayerChange")}else v7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=t7(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.A)(function(){j6("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.Eb("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.A)(function(){j6("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.Eb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);y7(this,"setVolume",e)}c.muted=b;c.volume=a;w7(this,c)}else v7(this,g.Ja(this.setVolume,a,b))};
g.h.Bz=function(a,b){if(1==this.g){var c=t7(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Sg(b.style),g.rc(d,c.l));y7(this,"setSubtitlesTrack",d);w7(this,c)}else v7(this,g.Ja(this.Bz,a,b))};
g.h.xs=function(a,b){if(1==this.g){y7(this,"setAudioTrack",{videoId:a,audioTrackId:b.fb.id});var c=t7(this);c.audioTrackId=b.fb.id;w7(this,c)}else v7(this,g.Ja(this.xs,a,b))};
g.h.xA=function(a,b){if(1==this.g){if(a&&b){var c=t7(this);o7(c,a,b);w7(this,c)}y7(this,"previous")}else v7(this,g.Ja(this.xA,a,b))};
g.h.wA=function(a,b){if(1==this.g){if(a&&b){var c=t7(this);o7(c,a,b);w7(this,c)}y7(this,"next")}else v7(this,g.Ja(this.wA,a,b))};
g.h.ju=function(){1==this.g?y7(this,"dismissAutoplay"):v7(this,this.ju)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.P("proxyStateChange",a,this.g)}s7.ya.dispose.call(this)};
g.h.V=function(){u7(this);this.A=null;this.B.clear();r7(this,null);s7.ya.V.call(this)};
g.h.ys=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.P("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,0==b.g.length&&(b.g=b.l,b.g.reverse(),b.l=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.lK=function(a,b){this.P(a,b)};
g.h.eI=function(a){if(!a)this.Dk(null),r7(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=t7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)j6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,w7(this,b)}};
g.h.Dk=function(a){j6("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.G);if(this.l=a)this.l.addUpdateListener(this.G),z7(this),this.P("remotePlayerChange")};
g.h.dI=function(a){a?(z7(this),this.P("remotePlayerChange")):this.Dk(null)};
g.h.qI=function(){var a=f7();a&&r7(this,a)};
g.h.Eb=function(a){j6("CP",a)};g.B(B7,g.O);g.h=B7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Na.listId=c);this.Na.videoId=d;this.Na.index=k||0;this.Na.state=3;m7(this.Na,m);this.A="UNSUPPORTED";C7("Connecting with setPlaylist and params: "+g.Sg(l));this.g.connect({method:"setPlaylist",params:g.Sg(l)},
a,O4())}else C7("Connecting without params"),this.g.connect({},a,O4());mma(this)};
g.h.dispose=function(){this.fa()||(this.P("beforeDispose"),D7(this,3));B7.ya.dispose.call(this)};
g.h.V=function(){E7(this);G7(this);F7(this);g.ir(this.H);this.H=window.NaN;g.ir(this.J);this.J=window.NaN;this.o=null;g.ys(this.U);this.U.length=0;this.g.dispose();B7.ya.V.call(this);this.A=this.F=this.l=this.Na=this.g=null};
g.h.JC=function(){this.C(2)};
g.h.iI=function(){C7("Channel opened");this.R&&(this.R=!1,F7(this),this.T=g.gr((0,g.A)(function(){C7("Timing out waiting for a screen.");this.C(1)},this),15E3));
Ila(Ula(this.g),this.Z)};
g.h.fI=function(){C7("Channel closed");(0,window.isNaN)(this.B)?R4(!0):R4();this.dispose()};
g.h.gI=function(a){R4();(0,window.isNaN)(this.G())?(C7("Channel error: "+a+" without reconnection"),this.dispose()):(this.R=!0,C7("Channel error: "+a+" with reconnection in "+this.G()+" ms"),D7(this,2))};
g.h.hI=function(a){a.params?C7("Received: action="+a.action+", params="+g.Sg(a.params)):C7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.kq(a.params.devices);this.l=(0,g.E)(a,function(a){return new z4(a)});
a=!!g.Pa(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
J7(this,a);break;case "loungeScreenDisconnected":g.Ya(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
J7(this,!1);break;case "remoteConnected":var b=new z4(g.kq(a.params.device));g.Pa(this.l,function(a){return b?a.id==b.id:!1})||g.Va(this.l,b);
break;case "remoteDisconnected":b=new z4(g.kq(a.params.device));g.Ya(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":K7(this,a);break;case "nowPlaying":pma(this,a);break;case "onStateChange":L7(this,a);break;case "onAdStateChange":qma(this,a);break;case "onVolumeChanged":rma(this,a);break;case "onSubtitlesTrackChanged":oma(this,a);break;case "nowAutoplaying":sma(this,a);break;case "autoplayDismissed":this.P("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.P("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.P("autoplayModeChange",this.A);"DISABLED"==this.A&&this.P("autoplayDismissed");break;case "onHasPreviousNextChanged":tma(this,a);break;case "requestAssistedSignIn":this.P("assistedSignInRequested",a.params.authCode);break;default:C7("Unrecognized action: "+a.action)}};
g.h.VL=function(){if(this.o){var a=this.o;this.o=null;this.Na.videoId!=a&&H7(this,"getNowPlaying")}};
B7.prototype.subscribe=B7.prototype.subscribe;B7.prototype.unsubscribeByKey=B7.prototype.Gc;B7.prototype.ia=function(){var a=3;this.fa()||(a=0,(0,window.isNaN)(this.G())?b6(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
B7.prototype.getProxyState=B7.prototype.ia;B7.prototype.C=function(a){C7("Disconnecting with "+a);E7(this);this.P("beforeDisconnect",a);1==a&&R4();a6(this.g,a);this.dispose()};
B7.prototype.disconnect=B7.prototype.C;B7.prototype.da=function(){var a=this.Na;this.o&&(a=this.Na.clone(),o7(a,this.o,a.index));return p7(a)};
B7.prototype.getPlayerContextData=B7.prototype.da;
B7.prototype.pa=function(a){var b=new j7(a);b.videoId&&b.videoId!=this.Na.videoId&&(this.o=b.videoId,g.ir(this.H),this.H=g.gr((0,g.A)(this.VL,this),5E3));var c=[];this.Na.listId==b.listId&&this.Na.videoId==b.videoId&&this.Na.index==b.index||c.push("remoteQueueChange");this.Na.g==b.g&&this.Na.volume==b.volume&&this.Na.muted==b.muted&&n7(this.Na)==n7(b)&&g.Sg(this.Na.l)==g.Sg(b.l)||c.push("remotePlayerChange");this.Na.reset(a);(0,g.C)(c,function(a){this.P(a)},this)};
B7.prototype.setPlayerContextData=B7.prototype.pa;B7.prototype.ba=function(){var a=this.g.C.id,b=g.Pa(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
B7.prototype.getOtherConnectedRemoteId=B7.prototype.ba;B7.prototype.G=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.D)():window.NaN};
B7.prototype.getReconnectTimeout=B7.prototype.G;B7.prototype.Y=function(){return this.A||"UNSUPPORTED"};
B7.prototype.getAutoplayMode=B7.prototype.Y;B7.prototype.ga=function(){return this.F||""};
B7.prototype.getAutoplayVideoId=B7.prototype.ga;B7.prototype.va=function(){if(!(0,window.isNaN)(this.G())){var a=this.g.l;g.aq(a.g);a.start()}};
B7.prototype.reconnect=B7.prototype.va;B7.prototype.na=function(a,b){H7(this,a,b);I7(this)};
B7.prototype.sendMessage=B7.prototype.na;g.B(M7,n6);g.h=M7.prototype;g.h.Id=function(a){return this.Cc.$_gs(a)};
g.h.contains=function(a){return!!this.Cc.$_c(a)};
g.h.get=function(a){return this.Cc.$_g(a)};
g.h.start=function(){this.Cc.$_st()};
g.h.add=function(a,b,c){this.Cc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Cc.$_r(a,b,c)};
g.h.Vn=function(a,b,c,d){this.Cc.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.l.length;a<b;++a)this.Cc.$_ubk(this.l[a]);this.l.length=0;this.Cc=null;M7.ya.V.call(this)};
g.h.WM=function(){this.P("screenChange")};
g.h.PJ=function(){this.P("onlineScreenChange")};
A6.prototype.$_st=A6.prototype.start;A6.prototype.$_gspc=A6.prototype.XM;A6.prototype.$_gsppc=A6.prototype.AA;A6.prototype.$_c=A6.prototype.contains;A6.prototype.$_g=A6.prototype.get;A6.prototype.$_a=A6.prototype.add;A6.prototype.$_un=A6.prototype.Vn;A6.prototype.$_r=A6.prototype.remove;A6.prototype.$_gs=A6.prototype.Id;A6.prototype.$_gos=A6.prototype.zA;A6.prototype.$_s=A6.prototype.subscribe;A6.prototype.$_ubk=A6.prototype.Gc;var N7=null,O7=null,d8=null,S7=[];g.r(g8,g.H);g.h=g8.prototype;
g.h.V=function(){g.H.prototype.V.call(this);this.o.stop();this.B.stop();this.J.stop();this.T();this.g.unsubscribe("proxyStateChange",this.my,this);this.g.unsubscribe("remotePlayerChange",this.Fk,this);this.g.unsubscribe("remoteQueueChange",this.fn,this);this.g.unsubscribe("autoplayUpNext",this.Lx,this);this.g.unsubscribe("previousNextChange",this.jy,this);this.g.unsubscribe("nowAutoplaying",this.ey,this);this.g.unsubscribe("autoplayDismissed",this.Kx,this);this.g=this.A=null};
g.h.Fw=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(k8(this)){if(!t7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==t7(this.g).g?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Rj(c[0],c[1]);break;case "control_subtitles_set_track":l8(this,c[0]);break;case "control_set_audio_track":c=c[0],k8(this)&&this.g.xs(this.L.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.L.getCurrentTime();m8(this,0==c?void 0:c);break;case "control_seek":m8(this,c[0]);break;case "control_subtitles_set_track":l8(this,c[0]);break;case "control_set_audio_track":c=c[0],k8(this)&&this.g.xs(this.L.getVideoData(1).videoId,c)}};
g.h.cI=function(a){this.J.EC(a)};
g.h.CM=function(a){this.Fw("control_subtitles_set_track",g.jc(a)?null:a)};
g.h.Nz=function(){var a=this.L.Vb("captions","track");g.jc(a)||l8(this,a)};
g.h.Zx=function(a){if(k8(this)){this.g.unsubscribe("remotePlayerChange",this.Fk,this);var b=Math.round(a.volume);a=!!a.muted;var c=t7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.N.start();this.g.subscribe("remotePlayerChange",this.Fk,this)}};
g.h.hJ=function(){g.jc(this.C)||n8(this,this.C);this.F=!1};
g.h.my=function(a,b){this.B.stop();2==b&&this.Lz()};
g.h.Fk=function(){if(k8(this)){this.o.stop();var a=t7(this.g);switch(a.g){case 1080:case 1081:case 1084:case 1085:this.A.G=1;break;case 1082:case 1083:this.A.G=0;break;default:this.A.G=-1}switch(a.g){case 1081:case 1:i8(this,new g.MC(8));this.Kz();break;case 1085:case 3:i8(this,new g.MC(9));break;case 1083:case 0:i8(this,new g.MC(2));this.H.stop();h8(this,this.L.getVideoData().lengthSeconds);break;case 1084:i8(this,new g.MC(4));break;case 2:i8(this,new g.MC(4));h8(this,n7(a));break;case -1:i8(this,
new g.MC(64));break;case -1E3:i8(this,new g.MC(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=t7(this.g).l;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,n8(this,a));a=t7(this.g);-1==a.volume||Math.round(this.L.Hb())==a.volume&&this.L.isMuted()==a.muted||this.N.isActive()||this.lA()}else j8(this)};
g.h.jy=function(){this.L.P("mdxpreviousnextchange")};
g.h.fn=function(){k8(this)||j8(this)};
g.h.aC=function(){this.g.ju()};
g.h.Lx=function(a){a&&(a=g.yr("/watch_queue_ajax",{method:"GET",zc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.nL,this)}))&&(this.T=(0,g.A)(a.abort,a))};
g.h.nL=function(a,b){var c=new g.CB(g.V(this.L),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.L.P("mdxautoplayupnext",c)};
g.h.ey=function(a){(0,window.isNaN)(a)||this.L.P("mdxnowautoplaying",a)};
g.h.Kx=function(){this.L.P("mdxautoplaycanceled")};
g.h.gG=function(a,b){-1==t7(this.g).g?m8(this,a):b&&this.g.seekTo(a)};
g.h.lA=function(){if(k8(this)){var a=t7(this.g);this.l.Ka(this.R);a.muted?this.L.mute():this.L.Xe();this.L.setVolume(a.volume);this.R=this.l.M(this.L,"onVolumeChange",this.Zx)}};
g.h.Kz=function(){this.o.stop();if(!this.g.fa()){var a=t7(this.g);1==a.g&&i8(this,new g.MC(8));h8(this,n7(a));this.o.start()}};
g.h.Lz=function(){this.B.stop();this.o.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.r(q8,g.Q);q8.prototype.A=function(a){p8(this,a.state)};g.r(r8,g.fS);r8.prototype.H=function(){var a=this.L.Vb("remote","receivers");a&&1<a.length&&!this.L.Vb("remote","quickCast")?(this.F=g.rb(a,this.A,this),g.gS(this,(0,g.E)(a,this.A)),a=this.L.Vb("remote","currentReceiver"),this.xe(this.A(a)),this.enable(!0)):this.enable(!1)};
r8.prototype.A=function(a){return a.key};
r8.prototype.we=function(a){return"cast-selector-receiver"==a?"Cast...":this.F[a].name};
r8.prototype.Tc=function(a){g.fS.prototype.Tc.call(this,a);this.L.gd("remote","currentReceiver",this.F[a]);this.o.ob()};g.r(s8,g.LJ);g.h=s8.prototype;g.h.create=function(){yma(g.Hz(g.V(this.g)));this.C.push(g.Ys("yt-remote-before-disconnect",this.ZH,this));this.C.push(g.Ys("yt-remote-connection-change",this.uK,this));this.C.push(g.Ys("yt-remote-receiver-availability-change",this.ky,this));this.C.push(g.Ys("yt-remote-auto-connect",this.sK,this));this.C.push(g.Ys("yt-remote-receiver-resumed",this.rK,this));this.ky()};
g.h.load=function(){this.g.zq();g.LJ.prototype.load.call(this);this.B=new g8(this,this.g,this.l);var a=(a=f8())?a.currentTime:0;var b=c8()?new s7(Y7(),void 0):null;0==a&&b&&(a=n7(t7(b)));0!=a&&this.od(a);o8(this,this.F,this.F);g.AV(this.g.app,6)};
g.h.unload=function(){this.g.P("mdxautoplaycanceled");this.A=this.o;g.mf(this.B,this.l);this.l=this.B=null;g.LJ.prototype.unload.call(this);g.AV(this.g.app,5)};
g.h.V=function(){g.Zs(this.C);g.LJ.prototype.V.call(this)};
g.h.bf=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.Fw.apply(this.B,[a].concat(g.pa(c)))};
g.h.BC=function(){return this.loaded?this.B.suggestion:null};
g.h.Te=function(){return this.l?t7(this.l).Te:!1};
g.h.hasNext=function(){return this.l?t7(this.l).hasNext:!1};
g.h.od=function(a,b){this.N=a||0;this.g.P("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.N};
g.h.WF=function(){var a=t7(this.l),b=this.g.getVideoData();return{allowSeeking:this.g.Ec(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.C?a.H+l7(a):a.H,ingestionTime:a.C?a.A+l7(a):a.A,isPeggedToLive:1>=(a.C?a.o+l7(a):a.o)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.C?a.o+l7(a):a.o,seekableStart:0<a.B?a.B+l7(a):a.B}};
g.h.XF=function(){this.l&&this.l.wA()};
g.h.YF=function(){this.l&&this.l.xA()};
g.h.ZH=function(a){1==a&&(this.J=this.l?t7(this.l):null)};
g.h.uK=function(){var a=c8()?new s7(Y7(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.J=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.lf(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.getVideoData().videoId&&this.g.hw(a.videoId,n7(a)));this.g.P("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.ky=function(){this.H=[this.o].concat(zma());var a=Z7()||this.o;t8(this,a);this.g.ma("onMdxReceiversChange")};
g.h.sK=function(){var a=Z7();t8(this,a)};
g.h.rK=function(){this.A=Z7()};
g.h.VF=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?h7():t8(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&h7(),!0):!1}};
g.h.ZF=function(){y7(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.fc=function(){return!1};g.qQ.remote=s8;})(_yt_player);
