$(document).ready(function(){jQuery.expr.filters.offscreen=function(el){return((el.offsetLeft+el.offsetWidth)<0||(el.offsetTop+el.offsetHeight)<0||(el.offsetLeft>window.innerWidth||el.offsetTop>window.innerHeight));};$(".navbar-toggle.main").click(function(){$("#languagebar").removeClass("in");$("#searchbar").removeClass("in");});$(".navbar-toggle.lang").click(function(){$("#menucontainer").removeClass("in");$("#searchbar").removeClass("in");});$(".navbar-toggle.search").click(function(){$("#menucontainer").removeClass("in");$("#languagebar").removeClass("in");});$('#pagination').click(function(event){$(window).scrollTop(0);});$('.select_filter').click(function(event){var state=false;if($(this).closest("li").find(".items").is(':hidden')){state=false;}else{state=true;}
$(".items").hide();if(state){$(this).closest("li").find(".items").hide();}else{$(this).closest("li").find(".items").show();}
$(this).find("i.switchClass").toggleClass("fa-angle-down");});$('.removefilter').click(function(){$(".switchClass").addClass("fa-angle-down");$('.items').hide();});if($('#back-to-top').length){var scrollTrigger=100,backToTop=function(){var scrollTop=$(window).scrollTop();if(scrollTop>scrollTrigger){$('#back-to-top').addClass('show');}else{$('#back-to-top').removeClass('show');}};backToTop();$(window).on('scroll',function(){backToTop();});$('#back-to-top').on('click',function(e){e.preventDefault();$('html,body').animate({scrollTop:0},700);});}
var previousScroll=0;var position=-60;$(document).on("scroll",onScroll);function onScroll(event){var scroll=$(this).scrollTop();var scrollPosition=$(document).scrollTop();var currentLink;$('nav#tableofcontent a').each(function(){currentLink=$(this);var refElement=$(currentLink.attr("href"));if(refElement.position().top<=scrollPosition&&refElement.position().top+refElement.height()>scrollPosition){if(!currentLink.closest('li').hasClass("active")){if(currentLink.closest('li').is(':offscreen')){$("#tableofcontent").css("top",position+"px");if(scroll>previousScroll){position=position-60;}else{if($("#tableofcontent").position().top<0){position=position+40;}else{$("#tableofcontent").css("top","10px");position=-60;}}}else{if($("#tableofcontent").position().top<0){$("#tableofcontent").css("top",position+"px");position=position+40;}else{position=-60;}}}
$('nav#tableofcontent ul li').removeClass("active");currentLink.closest('li').addClass("active");}
else{currentLink.closest('li').removeClass("active");}});previousScroll=scroll;}
$("#menucontainer .dropdown").on("hide.bs.dropdown",doNothing);$("#menucontainer .dropdown").on("show.bs.dropdown",doNothing);$(".show-languages.dropdown-toggle").click(function(event){event.preventDefault();$(this).find(".dropdown-menu").toggle();});function doNothing(e){if($(e.target).hasClass('parent_menu')){e.preventDefault();}}
setTimeout("$('#featured-header').fadeOut(500);",6000);$('.closeFilters').click(function(event){event.preventDefault();$('.filterHeader li').removeClass("selected");$('.sFilters').hide();});$('.choose_live > a').click(function(event){event.preventDefault();$('.choose_live > a').removeClass('now-playing-live');$(this).addClass('now-playing-live');$('.live_divs').hide();var id=$(this).data("id");$("#"+id).show();});if($(".child_menu.active").size()>0){$(".parent_menu").removeClass("open");$(".child_menu.active").closest(".parent_menu").addClass("open");}
var zoom=0;$('p').each(function(){var el=$(this),size=parseInt(el.css('font-size'));el.data('font-size',size);});$('button.decrease').click(function(){zoom--;$('p, pre, em, ul, ol, li').each(function(){var el=$(this),size=el.data('font-size');el.css('font-size',Math.max(size+zoom,0)+'px');});});$('button.increase').click(function(){zoom++;$('p, pre, em, ul, ol,li').each(function(){var el=$(this),size=el.data('font-size');el.css('font-size',Math.max(size+zoom,0)+'px');});});$(".switch-context").click(function(event){event.preventDefault();$(".switch-context").find("i").removeClass("playing");var div=$(this).data("display");$('.frame').hide();$("."+div).show();$('#youtube-player')[0].contentWindow.postMessage('{"event":"command","func":"'+'pauseVideo'+'","args":""}','*');$(this).find("i").addClass("playing");});$('.play_audio').click(function(event){event.preventDefault();var player=$('#audioPlayerWrap');var title=$(this).data("title");var author=$(this).data("author");player.find(".playing-title").html(title);player.find(".author").html(author);player.find("object").remove();var audio=$(this).attr("href");var audio_object='<object width="235" height="24" type="application/x-shockwave-flash" name="audioplayer" style="outline: medium none; visibility: visible;" data="http://cpmassets.com/audio-player.swf" id="audioplayer">'
audio_object+='<param name="wmode" value="opaque"><param name="menu" value="false">';audio_object+='<param  class="audio_pplayer_url" name="flashvars" value="autostart=yes&amp;soundFile='+audio+'&amp;playerID=audioplayer">';audio_object+='</object>';player.find(".audio-info").append(audio_object);player.show();});$('.close-icon').click(function(event){event.preventDefault();var player=$('#audioPlayerWrap');player.hide();player.find("object").remove();});$('.questions').click(function(event){event.preventDefault();var id=$(this).attr("answer-id");$("#"+id).toggle();});$('.show_sermons_for_series').click(function(event){event.preventDefault();$('.series-sermons-list').hide();var id=$(this).attr("n_id");$("#"+id).toggle();});$('.show_map').click(function(event){event.preventDefault();$('.modal').modal();$('#myModalLabel').html($(this).find(".locateus_from").html());$('.modal').find('iframe').attr('src',$(this).attr("iframe-src"));$('.modal').find('.bus-routes').html($(this).find(".bus-route").html()).show();if($(this).data("route")==true){$('.modal').find('.bus-route').hide();}
else{$('.modal').find('.bus-route').show();};});$('#subscribe_small_form').click(function(event){event.preventDefault();var email=$('#small_form_email').val();$('.wftw-subscription-form').toggle();$('#entry_1427445432').val(email);$('.wftw-subscription-form-detailed').toggle();$('.wftw-latest-title').toggle();});$('#small_form_email').keypress(function(event){var keycode=(event.keyCode?event.keyCode:event.which);if(keycode=='13'){var email=$('#small_form_email').val();$('.wftw-subscription-form').toggle();$('#mce-EMAIL').val(email);$('.wftw-subscription-form-detailed').toggle();}});$('.carousel-prev').click(function(event){event.preventDefault();var id=$(this).attr('carousel-id');var sly=$('#'+id).sly();sly.next();});$('.carousel-next').click(function(event){event.preventDefault();var id=$(this).attr('carousel-id');$('#'+id).carousel('next');$('#'+id).carousel('pause');});$('.close-wftw').click(function(event){event.preventDefault();$(".wftw-floating").hide();});if($(".books-chapter-titles").length){$('.books-chapter-titles a').click(function(){$('.books-chapter-titles li').removeClass("active");$(this).closest('li').addClass("active");$('html, body').animate({scrollTop:$($(this).attr('href')).offset().top},500);return false;});}
function findBootstrapEnvironment(){return $('#users-device-size').find('div:visible').first().attr('id');}
function menu_function(){$(".dropdown.active").toggleClass("open",true);var env=findBootstrapEnvironment();$("body").addClass(env);if(env=="xs"||env=="sm"){$(".dropdown").toggleClass("open",false);}}
$(function(){menu_function();});$('#menucontainer .dropdown-toggle').click(function(event){event.preventDefault();var env=findBootstrapEnvironment();console.log(env);var parent_li=$(this).closest('.dropdown');if(env=='xs'||env=='sm'){if(!parent_li.hasClass("open"))
$('#menucontainer .dropdown').removeClass("open");}else{$('#menucontainer .dropdown').removeClass("open");$('#menucontainer .dropdown-menu').hide();$(this).closest('.parent_menu').find('.dropdown-menu').fadeIn(600);}
$('.multi-column-dropdown').css("left","inherit");if(parent_li.hasClass("open"))
parent_li.toggleClass("open",false);else
parent_li.toggleClass("open",true);});$('.bs-docs-sidenav li').click(function(){current=$(this);setTimeout("$('.bs-docs-sidenav li').removeClass('active');current.addClass('active');",50);});function validateEmail(email){var re=/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;return re.test(email);}
$('#ss-form').submit(function(event){event.preventDefault();var name=$('#name').val();var email=$('#email').val();var gender=$('.ss-q-radio:checked').val();var location=$('#location').val();if((name!=="")&&(email!=="")&&((location!=="")&&(validateEmail(email)))){$.ajax({url:"https://docs.google.com/forms/d/1Fd3RZC6un2ZwTaZqBKozykJUmfpM48LHsirKlIKrvuM/formResponse",data:{"entry.1427445432":email,"entry.1757114485":name,"entry.1671840794":gender,"entry.2037088227":location},type:"POST",dataType:"xml",statusCode:{0:function(){$('.wftw-subscription-form-detailed').html("Successfully Submitted");},200:function(){$('.wftw-subscription-form-detailed').html("Successfully Submitted");}}});}
else{}});$('.apply-filter').click(function(event){event.preventDefault();$('.sermons').hide();filter_sermons($(this).data("type"),$(this).data("value"));});});function build_url(type){var d1=$("#category").find(":selected").attr("value");var d2=$("#author").find(":selected").attr("value");var d3=$("#sort").find(":selected").attr("value");var url=("/"+type+"/"+d1+"/"+d2+"/"+d3);window.location=url;return false;}
function animate_to_top(){$('html,body').animate({scrollTop:200},1000);return true;}
function play_audio(audio,title,author){var player=$('#audioPlayerWrap');player.find(".playing-title").html(title);player.find(".author").html(author);player.find("object").remove();var audio_object='<object width="235" height="24" type="application/x-shockwave-flash" name="audioplayer" style="outline: medium none; visibility: visible;" data="http://cpmassets.com/audio-player.swf" id="audioplayer">'
audio_object+='<param name="wmode" value="opaque"><param name="menu" value="false">';audio_object+='<param  class="audio_pplayer_url" name="flashvars" value="autostart=yes&amp;soundFile='+audio+'&amp;playerID=audioplayer">';audio_object+='</object>';player.find(".audio-info").append(audio_object);player.show();return false;}